<x-layouts::app :title="__('Certificates Management')">

<div class="space-y-6">

    <div>
        <h1 class="text-2xl font-bold">
            Certificates Management
        </h1>

        <p class="text-gray-500">
            View all certificates generated by students.
        </p>
    </div>

    <div class="rounded-xl border bg-white p-6 shadow-sm dark:bg-neutral-900 dark:border-neutral-700">

        <table class="w-full">

            <thead>
                <tr class="border-b">
                    <th class="p-3 text-left">Certificate No.</th>
                    <th class="p-3 text-left">Student</th>
                    <th class="p-3 text-left">Course</th>
                    <th class="p-3 text-left">Issued Date</th>
                </tr>
            </thead>

            <tbody>

                @forelse($certificates as $certificate)

                    <tr class="border-b">

                        <td class="p-3">
                            {{ $certificate->certificate_number }}
                        </td>

                        <td class="p-3">
                            {{ $certificate->student->name ?? '-' }}
                        </td>

                        <td class="p-3">
                            {{ $certificate->course->title ?? '-' }}
                        </td>

                        <td class="p-3">
                            {{ $certificate->created_at->format('M d, Y') }}
                        </td>

                    </tr>

                @empty

                    <tr>
                        <td colspan="4" class="p-4 text-center">
                            No certificates found.
                        </td>
                    </tr>

                @endforelse

            </tbody>

        </table>

        <div class="mt-4">
            {{ $certificates->links() }}
        </div>

    </div>

</div>

</x-layouts::app>